--- #YAML:1.0
name:                Catalyst-Plugin-Session-Store-MongoDB
version:             0.02
abstract:            MongoDB Session store for Catalyst
license:             ~
author:              
    - Stefan Völkel (bd@bc-bd.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst::Plugin::Session:     0.27
    Data::Dumper:                  0
    MongoDB:                       0
    Moose:                         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
